# Generated by Django 6.0.3 on 2026-03-18 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=80, unique=True)),
                ('kind', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('STARTED', 'Iniciado'), ('SUCCESS', 'Sucesso'), ('FAILURE', 'Falha')], db_index=True, default='PENDING', max_length=16)),
                ('requested_by', models.CharField(blank=True, default='', max_length=150)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('code', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('desktop', 'Desktop'), ('engine_api', 'Engine API'), ('django', 'Django')], default='django', max_length=16)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('days', models.IntegerField(default=1)),
                ('top', models.IntegerField(default=5)),
                ('min_books', models.IntegerField(default=8)),
                ('min_conf', models.FloatField(default=0.55)),
                ('min_edge', models.FloatField(default=0.01)),
                ('min_ev', models.FloatField(default=0.01)),
                ('market_thr', models.FloatField(default=0.45)),
                ('only_future', models.BooleanField(default=True)),
                ('status', models.CharField(db_index=True, default='running', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('kickoff', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('NS', 'Nao iniciado'), ('LIVE', 'Ao vivo'), ('FT', 'Encerrado'), ('AET', 'Prorrogacao'), ('PEN', 'Penaltis'), ('PST', 'Adiado'), ('CANC', 'Cancelado')], db_index=True, default='NS', max_length=8)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='api_sports', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='zhcore.league')),
            ],
            options={
                'ordering': ['-kickoff'],
            },
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('version', models.CharField(db_index=True, max_length=40)),
                ('path', models.CharField(max_length=320)),
                ('sha256', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_model_name_version')],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_best', models.FloatField(default=0.0)),
                ('p_market', models.FloatField(default=0.0)),
                ('p_model', models.FloatField(default=0.0)),
                ('p_api', models.FloatField(default=0.0)),
                ('p_final', models.FloatField(default=0.0)),
                ('edge', models.FloatField(default=0.0)),
                ('ev', models.FloatField(default=0.0)),
                ('conf', models.FloatField(default=0.0)),
                ('score', models.FloatField(default=0.0)),
                ('books', models.IntegerField(default=0)),
                ('tier', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='C', max_length=1)),
                ('why_entered', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='zhcore.match')),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='zhcore.scansession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('O', 'Aberta'), ('G', 'Ganho'), ('P', 'Perda'), ('E', 'Empate'), ('V', 'Void')], db_index=True, default='O', max_length=1)),
                ('profit', models.FloatField(default=0.0)),
                ('settled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='zhcore.opportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=140)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='uniq_team_name_country')],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='underdog_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='underdog_opportunities', to='zhcore.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='zhcore.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='zhcore.team'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['scan_session', '-score'], name='zhcore_oppo_scan_se_b91ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['-ev', '-edge'], name='zhcore_oppo_ev_c9b009_idx'),
        ),
    ]
