# Generated by Django 6.0.3 on 2026-03-19 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zhcore", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovada"),
                            ("rejected", "Rejeitada"),
                            ("published", "Publicada"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "public_reason",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("private_note", models.TextField(blank=True, default="")),
                ("risk_note", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="zhcore.opportunity",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PublishedPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=240, unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=220)),
                (
                    "short_reason",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("public_note", models.TextField(blank=True, default="")),
                (
                    "visibility",
                    models.CharField(
                        choices=[("members", "Membros"), ("private", "Privada")],
                        db_index=True,
                        default="members",
                        max_length=16,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "kickoff_snapshot",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "league_name_snapshot",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "country_snapshot",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "home_team_snapshot",
                    models.CharField(blank=True, default="", max_length=140),
                ),
                (
                    "away_team_snapshot",
                    models.CharField(blank=True, default="", max_length=140),
                ),
                (
                    "underdog_snapshot",
                    models.CharField(blank=True, default="", max_length=140),
                ),
                ("odd_snapshot", models.FloatField(default=0.0)),
                ("ev_snapshot", models.FloatField(default=0.0)),
                ("edge_snapshot", models.FloatField(default=0.0)),
                ("conf_snapshot", models.FloatField(default=0.0)),
                ("p_final_snapshot", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("live", "Ao vivo"),
                            ("won", "Ganha"),
                            ("lost", "Perdida"),
                            ("draw", "Empate"),
                            ("void", "Void"),
                            ("archived", "Arquivada"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                (
                    "result_label",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                ("result_profit", models.FloatField(default=0.0)),
                ("priority", models.IntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "settled_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_pick",
                        to="zhcore.opportunity",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_picks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Membro"),
                            ("analyst", "Analista"),
                            ("admin", "Administrador"),
                        ],
                        db_index=True,
                        default="member",
                        max_length=16,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(default="pt-BR", max_length=16),
                ),
                ("is_portal_active", models.BooleanField(db_index=True, default=True)),
                ("accepted_terms_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
            },
        ),
    ]
