# Generated by Django 6.0.3 on 2026-03-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zhcore", "0002_opportunityreview_publishedpick_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="score_breakdown",
            field=models.TextField(blank=True, default=""),
        ),
    ]
