# Generated by Django 6.0.3 on 2026-04-10 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zhcore", "0003_opportunity_score_breakdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                ("full_name", models.CharField(blank=True, default="", max_length=160)),
                (
                    "external_reference",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                (
                    "preferred_language",
                    models.CharField(default="pt-BR", max_length=16),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "first_seen_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("last_seen_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "ordering": ["email", "external_reference"],
            },
        ),
        migrations.CreateModel(
            name="LicensePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("price_cents", models.PositiveIntegerField(default=2900)),
                ("currency", models.CharField(default="BRL", max_length=8)),
                ("billing_days", models.PositiveIntegerField(default=30)),
                ("trial_days", models.PositiveIntegerField(default=30)),
                ("max_devices", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LicenseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Ativa"),
                            ("past_due", "Pagamento pendente"),
                            ("expired", "Expirada"),
                            ("cancelled", "Cancelada"),
                            ("blocked", "Bloqueada"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("trial", "Trial"),
                            ("mercado_pago", "Mercado Pago"),
                            ("admin", "Admin"),
                            ("migration", "Migracao"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("max_devices", models.PositiveIntegerField(default=1)),
                ("issued_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "activated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "last_validated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "mercado_pago_external_reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "mercado_pago_preference_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licenses",
                        to="zhcore.licensecustomer",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licenses",
                        to="zhcore.licenseplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "install_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(db_index=True, max_length=120, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Ativo"),
                            ("blocked", "Bloqueado"),
                            ("revoked", "Revogado"),
                        ],
                        db_index=True,
                        default="trial",
                        max_length=16,
                    ),
                ),
                ("hostname", models.CharField(blank=True, default="", max_length=160)),
                ("platform", models.CharField(blank=True, default="", max_length=80)),
                ("app_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "app_version",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "trial_started_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "trial_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("checkout_url", models.URLField(blank=True, default="")),
                (
                    "checkout_preference_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("checkout_created_at", models.DateTimeField(blank=True, null=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "first_seen_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("last_seen_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="zhcore.licensecustomer",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="zhcore.licenseplan",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="zhcore.licenserecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True, default="mercado_pago", max_length=40
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=80
                    ),
                ),
                ("action", models.CharField(blank=True, default="", max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("authorized", "Autorizado"),
                            ("rejected", "Rejeitado"),
                            ("cancelled", "Cancelado"),
                            ("refunded", "Estornado"),
                            ("unknown", "Desconhecido"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("amount", models.FloatField(default=0.0)),
                ("currency", models.CharField(default="BRL", max_length=8)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_events",
                        to="zhcore.licensecustomer",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_events",
                        to="zhcore.licenserecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("payment_id", ""), _negated=True),
                        fields=("provider", "payment_id"),
                        name="uniq_payment_provider_payment_id",
                    )
                ],
            },
        ),
    ]
